#!/usr/bin/env bash

DOTFILES=~/.dotfiles # hardcode for now

ln -sfv $DOTFILES/vimrc ~/.vimrc
ln -sfv $DOTFILES/tmux.conf ~/.tmux.conf
ln -sfv $DOTFILES/bashrc ~/.bashrc
ln -sfv $DOTFILES/bash_profile ~/.bash_profile
ln -sfv $DOTFILES/gdbinit ~/.gdbinit

if [[ -d "~/.config/nvim" ]]; then
    ln -sfv $DOTFILES/vimrc $HOME/.config/nvim
fi
